---
:hardlink: true
:hardlink_dir: '/mirror'
:mirrors:
  centos-7-x86-os:
    :type: 'rsync'
    :url: 'rsync://mirrors.kernel.org/centos/centos7/os/x86_64/'
    :dest: '/mirror/centos-7-x86_64/os'
    :datestamp: true
    :hardlink_datestamp: true
  centos-7-x86-64-extras:
    :type: 'rsync'
    :url: 'rsync://mirrors.kernel.org/centos/centos/7/extras/x86_64/'
    :dest: '/mirror/centos-7-x86_64/extras'
    :datestamp: true
    :hardlink_datestamp: true
  centos-7-x86-64-plus:
    :type: 'rsync'
    :url: 'rsync://mirrors.kernel.org/centos/centos/7/centosplus/x86_64/'
    :dest: '/mirror/centos-7-x86_64/centosplus'
    :datestamp: true
    :hardlink_datestamp: true
  centos-7-x86-64-updates:
    :type: 'rsync'
    :url: 'rsync://mirrors.kernel.org/centos/centos/7/updates/x86_64/'
    :dest: '/mirror/centos-7-x86_64/updates'
    :datestamp: true
    :hardlink_datestamp: true
  centos-7-x86_64-scl:
    :type: 'rsync'
    :url: 'rsync://mirrors.kernel.org/centos/centos/7/sclo/x86_64/rh/'
    :dest: '/mirror/centos-7-x86_64/scl'
    :datestamp: true
    :hardlink_datestamp: true
  epel-7-x86_64:
    :type: 'rsync'
    :url: 'rsync://mirror.us.leaseweb.net/epel/7/x86_64/'
    :dest: '/mirror/centos-7-x86_64/epel'
    :datestamp: true
    :hardlink_datestamp: true
  puppetlabs-pc1-7-x86-64:
    :type: 'rsync'
    :url: 'rsync://yum.puppetlabs.com/packages/yum/el/7/PC1/x86_64/'
    :dest: '/mirror/centos-7-x86_64/pc1'
#  centos-6-x86-os:
#    :type: 'rsync'
#    :url: 'rsync://mirrors.kernel.org/centos/centos/6/os/x86_64/'
#    :dest: '/mirror/centos-6-x86_64/os/'
#  centos-7-x86-os:
#    :type: 'reposync'
#    :url: 'http://mirrors.tripadvisor.com/centos/7/os/x86_64/'
#    :dest: '/mirror/centos-7-x86_64/os'
