---
:hardlink: true
:hardlink_dir: '/mirror'
:mirrors:
  centos-7-x86-64-extras:
    :type: 'reposync'
    :url: 'http://mirrors.tripadvisor.com/centos/7/extras/x86_64/'
    :dest: '/mirror/centos-7-x86_64/extras'
    :datestamp: true
    :hardlink_datestamp: true
    :link_datestamp: false
  puppetlabs-pc1-7-x86-64:
    :type: 'rsync'
    :url: 'rsync://yum.puppetlabs.com/packages/yum/el/7/PC1/x86_64/'
    :dest: '/mirror/centos-7-x86_64/pc1'
    :datestamp: true
    :link_datestamp: false
  puppetlabs-pc1-6-x86-64:
    :type: 'rsync'
    :url: 'rsync://yum.puppetlabs.com/packages/yum/el/6/PC1/x86_64/'
    :dest: '/mirror/centos-6-x86_64/pc1'
#  centos-6-x86-os:
#    :type: 'rsync'
#    :url: 'rsync://mirrors.tripadvisor.com/centos/6/os/x86_64/'
#    :dest: '/mirror/centos-6-x86_64/os/'
#  centos-7-x86-os:
#    :type: 'reposync'
#    :url: 'http://mirrors.tripadvisor.com/centos/7/os/x86_64/'
#    :dest: '/mirror/centos-7-x86_64/os'
